name: CloudTechTodays
favicon: null
layout_spectrum: 0.49004359846003354
typography_spectrum: 0.5418325455393642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8928173366002738
  lightness: 0.41350189689546824
  saturation: 0.09652656479738653
  rhythmicContrast: 0.6761688864789903
purpose: []
